### ISSUE TITLE
Incorrect JSON in purchase import job

### ISSUE THREAD

**Issue by paul-muckypuddle** [marcelhamel/sailthru-postman#1]
The JSON at

https://github.com/marcelhamel/sailthru-postman/blob/3d228653a83d9029ef67a5d8f13388b775cf2fc3/Sailthru%20API.postman_collection.json#L652

is invalid, should be:

` "value": "{\"job\":\"purchase_import\", \"convert_numeric_strings\": false}", `

**Comment by marcelhamel** [comment]
Thanks for flagging, Paul. Just made this change.
